Repository winglang/wing, pull requests merged in 2023-01, with the labels that each got.

#1030 feat(compiler): basic global utility functions
  docs/06-contributors/handbook.md
  examples/tests/error/utilities.w
  libs/wingc/src/ast.rs
  libs/wingc/src/jsify.rs
  libs/wingc/src/lib.rs
  tools/hangar/src/__snapshots__/cli.test.ts.snap
  tools/hangar/src/cli.test.ts
Labels: compiler

#1176 chore(docs): markdown error br
  docs/02-getting-started/02-installation.md
Labels: documentation

#1196 fix(compiler): no error when trying to reassign to a `let` variable
  docs/04-reference/winglang-spec.md
  examples/tests/invalid/reassing_to_nonreassignable.w
  examples/tests/valid/anon_function.w
  examples/tests/valid/reassignment.w
  libs/tree-sitter-wing/grammar.js
  libs/tree-sitter-wing/test/corpus/statements.txt
  libs/wingc/src/ast.rs
  libs/wingc/src/capture.rs
  libs/wingc/src/jsify.rs
  libs/wingc/src/lib.rs
  libs/wingc/src/parser.rs
  libs/wingc/src/type_check.rs
  libs/wingc/src/type_check/jsii_importer.rs
  libs/wingc/src/type_check/symbol_env.rs
  tools/hangar/src/__snapshots__/cli.test.ts.snap
Labels: do-not-merge

#1262 fix(compiler): empty set initialization
  examples/tests/invalid/reassign_to_nonreassignable.w
  examples/tests/valid/container_types.w
  libs/wingc/src/parser.rs
  tools/hangar/src/__snapshots__/cli.test.ts.snap
Labels: compiler
