Repository winglang/wing, pull requests merged in 2023-08, with the labels that each got.

#3567 fix(compiler): improve JSII loading speed via binary format cache
  .gitignore
  Cargo.lock
  apps/wing/src/commands/compile.ts
  libs/wingc/src/type_check/jsii_importer.rs
  libs/wingcompiler/src/compile.ts
  libs/wingii/Cargo.toml
  libs/wingii/src/jsii.rs
  libs/wingii/src/lib.rs
  libs/wingii/src/node_resolve.rs
  libs/wingii/src/test.rs
  tools/hangar/src/jsii_cache.test.ts
  tools/hangar/src/paths.ts
Labels: 🧪 pr/e2e-full, ⚠️ pr/review-mutation

#3646 feat(cli): disable test cleanup with a `--no-clean` flag
  apps/wing/src/cli.ts
  apps/wing/src/commands/test.ts
  docs/docs/02-concepts/04-tests.md
Labels: 🧪 pr/e2e-full

#3815 chore(repo): ensure certain sdk docs cannot be merged without running build
  .github/workflows/pull-request-lint.yml
  .mergify.yml
Labels: ⚠️ mergify/review-config

#3876 chore(repo): typo in mergify queue message
  .mergify.yml
Labels: ⚠️ mergify/review-config

#4009 chore(compiler): store paths with Utf8PathBuf
  Cargo.lock
  libs/wingc/Cargo.toml
  libs/wingc/examples/compile.rs
  libs/wingc/src/file_graph.rs
  libs/wingc/src/files.rs
  libs/wingc/src/jsify.rs
  libs/wingc/src/lib.rs
  libs/wingc/src/lsp/completions.rs
  libs/wingc/src/lsp/document_symbols.rs
  libs/wingc/src/lsp/goto_definition.rs
  libs/wingc/src/lsp/hover.rs
  libs/wingc/src/lsp/signature.rs
  libs/wingc/src/lsp/sync.rs
  libs/wingc/src/parser.rs
  libs/wingc/src/test_utils.rs
  libs/wingc/src/type_check.rs
  libs/wingii/Cargo.toml
  libs/wingii/src/lib.rs
  libs/wingii/src/node_resolve.rs
  libs/wingii/src/test.rs
  libs/wingii/src/util.rs
Labels: 🧪 pr/e2e-full
