Repository winglang/wing, pull requests merged in 2023-07, with the labels that each got.

#3153 feat(sdk): bool & string tests
  examples/tests/sdk_tests/std/bool.w
  examples/tests/sdk_tests/std/string.w
  tools/hangar/__snapshots__/test_corpus/sdk_tests/std/bool.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/std/bool.w_test_sim.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/std/string.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/std/string.w_test_sim.md
Labels: 🎨 sdk, 🧪 testing

#3367 fix: lazy importing perf improvements
  apps/wing/jest.config.js
  apps/wing/package.json
  apps/wing/src/cli.ts
  apps/wing/src/commands/lsp.ts
  apps/wing/src/commands/test.ts
  apps/wing/src/commands/upgrade.ts
  apps/wing/src/index.ts
  apps/wing/src/util.ts
  apps/wing/src/wingc.ts
  libs/tree-sitter-wing/project.json
  libs/wingc/project.json
  libs/wingcompiler/package.json
  libs/wingcompiler/project.json
  libs/wingcompiler/tsup.config.ts
  libs/wingii/project.json
  libs/wingsdk/src/target-sim/factory.inflight.ts
  nx.json
  package.json
  patches/wasi-js@1.7.3.patch
  pnpm-lock.yaml
  tools/hangar/src/unsupported.test.ts
  tools/hangar/vitest.config.ts
Labels: 🧪 pr/e2e-full

#3360 chore(docs): ci/cd guide
  docs/docs/08-guides/02-ci-cd.md
Labels: pr/backport

#3415 chore: fix topic title
  docs/docs/07-examples/04-flow-controls.md
Labels: pr/backport

#3403 fix(docs): post code freeze small issues
  docs/docs/01-start-here/01-getting-started.md
  docs/docs/01-start-here/02-installation.md
  docs/docs/01-start-here/03-hello.md
  docs/docs/01-start-here/04-run-locally.md
  docs/docs/01-start-here/05-aws.md
  docs/docs/06-tools/02-wing-console.md
Labels: pr/backport

#3419 chore(console): clean version prints to console
  apps/wing-console/console/server/src/utils/getWingVersion.ts
Labels: pr/backport

#3428 fix(vscode): lsp crashes when a non-spanned diagnostics is encountered
  apps/wing/src/commands/compile.ts
  apps/wing/src/commands/lsp.ts
  libs/wingcompiler/src/wingc.ts
Labels: pr/backport

#3430 fix(docs): analytic opt-out env var outdated
  docs/docs/09-analytics.md
Labels: pr/backport

#3427 chore: remove release commenter for now
  .github/workflows/release-commenter.yml
Labels: pr/backport

#3432 chore: enable speculative merges
  .mergify.yml
Labels: ⚠️ mergify/review-config

#3439 fix(cli): display analytics disclaimer only in tty
  apps/wing/src/analytics/disclaimer.test.ts
  apps/wing/src/analytics/disclaimer.ts
  apps/wing/src/analytics/storage.ts
Labels: pr/backport

#3445 chore(docs): update terraform backend guide
  docs/docs/08-guides/01-terraform-backend.md
Labels: pr/backport

#3452 chore(repo): disable analytics for canary
  .github/workflows/canary.yml
Labels: pr/backport

#3460 chore(console): disable console analytics for ci
  apps/wing-console/console/app/src/index.ts
  apps/wing-console/console/app/tsup.config.ts
Labels: ⚠️ pr/review-mutation, pr/backport

#3462 chore(console): remove white spaces from analytics events
  apps/wing-console/console/app/src/analytics.ts
Labels: ⚠️ pr/review-mutation, pr/backport

#3465 chore(docs): modified compiler target code example
  docs/docs/02-concepts/03-compile-targets.md
Labels: pr/backport

#3467 fix(docs): typo in docs
  docs/docs/02-concepts/03-compile-targets.md
Labels: pr/backport

#3471 chore(docs): fix examples
  docs/docs/07-examples/01-variable-declaration.md
  docs/docs/07-examples/02-primitives.md
  docs/docs/07-examples/03-functions.md
Labels: pr/backport

#3479 chore(console): update terms and conditions license
  apps/wing-console/LICENSE.md
  apps/wing-console/console/design-system/package.json
  apps/wing-console/console/ui/package.json
Labels: pr/backport

#3485 fix: url shortener not compiling
  examples/proposed/url-shortener.js
  examples/proposed/url-shortener.w
Labels: pr/backport

#3490 chore: contribution license update
  .github/pull_request_template.md
  CONTRIBUTION_LICENSE.md
  apps/wing-console/LICENSE.md
Labels: pr/backport

#3487 chore: tweaks to docs
  docs/docs/01-start-here/01-getting-started.md
Labels: pr/backport

#3478 chore(docs): refresh README and docs landing page
  README.md
  apps/wing/README.md
  docs/docs/01-start-here/01-getting-started.md
  docs/docs/02-concepts/03-compile-targets.md
  docs/docs/02-concepts/05-simulator.md
  docs/docs/04-standard-library/01-cloud/_category_.yml
  docs/docs/999-faq/010-good-fit.md
  docs/docs/999-faq/020-supported-clouds-services-and-engines/022-supported-services.md
Labels: pr/backport

#3516 chore(docs): update legal
  .github/pull_request_template.md
  CONTRIBUTION_LICENSE.md
  CONTRIBUTORS_TERMS_OF_SERVICE.md
  apps/wing-console/LICENSE.md
Labels: pr/backport

#3510 fix(compiler): `@inflight` docstring on methods was ignored by the jsii_importer
  examples/tests/invalid/call_inflight_from_preflight.w
  libs/wingc/src/lsp/snapshots/completions/namespace_inflight.snap
  libs/wingc/src/lsp/snapshots/completions/util_static_methods.snap
  libs/wingc/src/type_check/jsii_importer.rs
  tools/hangar/__snapshots__/invalid.ts.snap
Labels: ⚠️ pr/review-mutation

#3519 chore: tweaks to getting started
  docs/docs/01-start-here/02-installation.md
  docs/docs/01-start-here/03-hello.md
  docs/docs/01-start-here/04-run-locally.md
Labels: pr/backport

#3523 fix(docs): link to cloud library documentation is incorrect
  README.md
  apps/wing/README.md
Labels: pr/backport

#3551 fix(docs): enhancing the getting-started app on the docs
  docs/docs/01-start-here/03-hello.md
  docs/docs/01-start-here/04-run-locally.md
  docs/docs/01-start-here/05-aws.md
  docs/docs/01-start-here/console-app.png
  docs/docs/01-start-here/console-bucket-1.png
  docs/docs/01-start-here/console-queue.png
Labels: 📚 documentation, ✨ enhancement, pr/backport

#3554 chore(docs): good first issue emoji removed
  docs/contributing/01-start-here/01-contributing-to-wing.md
Labels: pr/backport

#3560 chore: unfreeze main branch
  .mergify.yml
Labels: ⚠️ mergify/review-config

#3650 chore(docs): update contribution license in readme
  README.md
  apps/wing/README.md
Labels: ⚠️ pr/review-mutation
