Repository winglang/wing, pull requests merged in 2023-11, with the labels that each got.

#4697 feat(sdk)!: expose simulated resources via HTTP server (attempt 2)
  .github/workflows/build.yml
  apps/wing/src/commands/compile.test.ts
  apps/wing/src/commands/pack.test.ts
  apps/wing/src/commands/run.test.ts
  apps/wing/src/commands/test/test.test.ts
  docs/docs/04-standard-library/02-ex/redis.md
  examples/tests/sdk_tests/bucket/delete.test.w
  examples/tests/sdk_tests/bucket/load_test.test.w
  examples/tests/sdk_tests/bucket/metadata.test.w
  examples/tests/sdk_tests/bucket/public_url.test.w
  examples/tests/sdk_tests/queue/push.test.w
  examples/tests/sdk_tests/schedule/on_tick.test.w
  examples/tests/sdk_tests/table/get.test.w
  examples/tests/valid/redis.test.w
  libs/wingcompiler/src/compile.ts
  libs/wingsdk/.projen/deps.json
  libs/wingsdk/.projen/tasks.json
  libs/wingsdk/.projenrc.ts
  libs/wingsdk/package.json
  libs/wingsdk/src/ex/redis.ts
  libs/wingsdk/src/shared/bundling.ts
  libs/wingsdk/src/shared/sandbox.ts
  libs/wingsdk/src/simulator/client.ts
  libs/wingsdk/src/simulator/index.ts
  libs/wingsdk/src/simulator/simulator.ts
  libs/wingsdk/src/std/datetime.ts
  libs/wingsdk/src/target-sim/function.inflight.ts
  libs/wingsdk/src/target-sim/redis.ts
  libs/wingsdk/src/target-sim/service.inflight.ts
  libs/wingsdk/src/target-sim/util.ts
  libs/wingsdk/src/target-tf-aws/redis.inflight.ts
  libs/wingsdk/src/target-tf-aws/redis.ts
  libs/wingsdk/test/simulator/__snapshots__/simulator.test.ts.snap
  libs/wingsdk/test/simulator/simulator.test.ts
  libs/wingsdk/test/target-sim/__snapshots__/bucket.test.ts.snap
  libs/wingsdk/test/target-sim/__snapshots__/file-counter.test.ts.snap
  libs/wingsdk/test/target-sim/__snapshots__/function.test.ts.snap
  libs/wingsdk/test/target-sim/__snapshots__/immutable-capture.test.ts.snap
  libs/wingsdk/test/target-sim/__snapshots__/queue.test.ts.snap
  libs/wingsdk/test/target-sim/__snapshots__/topic.test.ts.snap
  libs/wingsdk/test/target-sim/bucket.test.ts
  libs/wingsdk/test/target-sim/file-counter.test.ts
  libs/wingsdk/test/target-sim/function.test.ts
  libs/wingsdk/test/target-sim/queue.test.ts
  libs/wingsdk/test/target-sim/redis.test.ts
  libs/wingsdk/test/target-sim/state.test.ts
  libs/wingsdk/test/target-sim/topic.test.ts
  pnpm-lock.yaml
  tools/hangar/__snapshots__/test_corpus/sdk_tests/bucket/load_test.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/bucket/load_test.test.w_test_sim.md
  tools/hangar/__snapshots__/test_corpus/valid/bucket_events.test.w_test_sim.md
  tools/hangar/__snapshots__/test_corpus/valid/redis.test.w_compile_tf-aws.md
Labels: 🧪 pr/e2e-full

#4740 chore(sdk)!: rename `Props` to `Options` for functions and methods
  docs/docs/04-standard-library/01-cloud/api.md
  docs/docs/04-standard-library/01-cloud/bucket.md
  docs/docs/04-standard-library/01-cloud/queue.md
  docs/docs/04-standard-library/01-cloud/schedule.md
  docs/docs/04-standard-library/01-cloud/service.md
  docs/docs/04-standard-library/01-cloud/topic.md
  docs/docs/04-standard-library/02-ex/dynamodb-table.md
  libs/wingc/src/lsp/snapshots/completions/incomplete_inflight_namespace.snap
  libs/wingc/src/lsp/snapshots/completions/namespace_middle_dot.snap
  libs/wingc/src/lsp/snapshots/completions/new_expression_nested.snap
  libs/wingc/src/lsp/snapshots/completions/partial_type_reference_annotation.snap
  libs/wingc/src/lsp/snapshots/completions/variable_type_annotation_namespace.snap
  libs/wingc/src/lsp/snapshots/hovers/class_symbol.snap
  libs/wingc/src/lsp/snapshots/hovers/inside_class_field.snap
  libs/wingc/src/lsp/snapshots/hovers/new_statement.snap
  libs/wingsdk/src/cloud/api.ts
  libs/wingsdk/src/cloud/bucket.ts
  libs/wingsdk/src/cloud/queue.ts
  libs/wingsdk/src/cloud/schedule.ts
  libs/wingsdk/src/cloud/service.ts
  libs/wingsdk/src/cloud/topic.ts
  libs/wingsdk/src/ex/dynamodb-table.ts
  libs/wingsdk/src/target-awscdk/bucket.ts
  libs/wingsdk/src/target-awscdk/queue.ts
  libs/wingsdk/src/target-awscdk/schedule.ts
  libs/wingsdk/src/target-awscdk/topic.ts
  libs/wingsdk/src/target-sim/api.ts
  libs/wingsdk/src/target-sim/queue.ts
  libs/wingsdk/src/target-sim/schedule.ts
  libs/wingsdk/src/target-sim/topic.ts
  libs/wingsdk/src/target-tf-aws/api.ts
  libs/wingsdk/src/target-tf-aws/queue.ts
  libs/wingsdk/src/target-tf-aws/schedule.ts
  libs/wingsdk/src/target-tf-aws/topic.ts
  libs/wingsdk/src/target-tf-azure/bucket.ts
  libs/wingsdk/src/target-tf-gcp/bucket.ts
Labels: breaking-change

#4798 fix(cli): wing pack doesn't pack subdirectories
  apps/wing/fixtures/invalid3/package.json
  apps/wing/fixtures/invalid4/file1.w
  apps/wing/fixtures/invalid4/file2.w
  apps/wing/fixtures/invalid4/package.json
  apps/wing/fixtures/valid1/main.w
  apps/wing/fixtures/valid1/package.json
  apps/wing/fixtures/valid1/util.ts
  apps/wing/package.json
  apps/wing/src/commands/pack.test.ts
  apps/wing/src/commands/pack.ts
  examples/wing-fixture/LICENSE
  examples/wing-fixture/util.ts
  pnpm-lock.yaml
Labels: 🧪 pr/e2e-full

#4855 chore(cli): small tweak for test command
  apps/wing/src/commands/test/test.ts
Labels: 🧪 pr/e2e-full

#4879 fix(sdk): avoid cyclic dependencies when api url is referenced
  libs/wingsdk/src/target-tf-aws/api.ts
  libs/wingsdk/test/target-tf-aws/__snapshots__/tokens.test.ts.snap
  libs/wingsdk/test/target-tf-aws/api.test.ts
  tools/hangar/__snapshots__/test_corpus/sdk_tests/website/react-app.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/api.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/website_with_api.test.w_compile_tf-aws.md
Labels: :dog: dogfood

#4886 fix(sdk): regression in api url
  libs/wingsdk/src/target-tf-aws/api.ts
  libs/wingsdk/test/target-tf-aws/__snapshots__/tokens.test.ts.snap
  libs/wingsdk/test/target-tf-aws/api.test.ts
  tools/hangar/__snapshots__/test_corpus/sdk_tests/website/react-app.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/api.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/website_with_api.test.w_compile_tf-aws.md
Labels: :dog: dogfood

#4888 fix(sdk): make sure the api gateway is recreated before destroying
  libs/wingsdk/src/target-tf-aws/api.ts
  libs/wingsdk/test/target-tf-aws/__snapshots__/tokens.test.ts.snap
  tools/hangar/__snapshots__/test_corpus/sdk_tests/api/404.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/api/cors.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/api/delete.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/api/get.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/api/options.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/api/patch.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/api/path_vars.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/api/post.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/api/put.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/website/react-app.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/api.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/api_cors_custom.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/api_cors_default.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/api_valid_path.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/capture_tokens.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/captures.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/inference.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/inherit_stdlib_class.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/issue_2889.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/website_with_api.test.w_compile_tf-aws.md
Labels: :dog: dogfood

#4878 feat(sdk): add missing utilities for `fs` module
  docs/docs/04-standard-library/03-std/api-reference.md
  docs/docs/04-standard-library/10-fs/api-reference.md
  examples/tests/sdk_tests/fs/directory.test.w
  examples/tests/sdk_tests/fs/path.test.w
  examples/tests/sdk_tests/fs/stat.test.w
  libs/wingsdk/src/fs/fs.ts
  libs/wingsdk/src/std/datetime.ts
  tools/hangar/__snapshots__/test_corpus/sdk_tests/fs/directory.test.w_test_sim.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/fs/path.test.w_test_sim.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/fs/stat.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/fs/stat.test.w_test_sim.md
Labels: 🧪 pr/e2e-full

#5035 chore(sdk): fix node.test.w test on windows
  examples/tests/sdk_tests/std/node.test.w
Labels: 🧪 pr/e2e-full

#5041 fix(sdk): relative imports for external platforms
  examples/tests/valid/platforms/local-package/a-relative-platform.js
  examples/tests/valid/platforms/local-package/index.js
  libs/wingsdk/src/platform/platform-manager.ts
  tools/hangar/src/platform.test.ts
Labels: 👠 platforms, 🐶 dogfood

#5046 feat(compiler): allow map keys to be any string expression
  docs/docs/03-language-reference.md
  examples/tests/invalid/container_types.test.w
  examples/tests/valid/container_types.test.w
  libs/tree-sitter-wing/grammar.js
  libs/tree-sitter-wing/test/corpus/expressions.txt
  libs/wingc/src/ast.rs
  libs/wingc/src/fold.rs
  libs/wingc/src/jsify.rs
  libs/wingc/src/jsify/snapshots/access_property_on_value_returned_from_collection.snap
  libs/wingc/src/lsp/hover.rs
  libs/wingc/src/lsp/snapshots/hovers/map_element.snap
  libs/wingc/src/lsp/symbol_locator.rs
  libs/wingc/src/parser.rs
  libs/wingc/src/type_check.rs
  libs/wingc/src/visit.rs
  tools/hangar/__snapshots__/invalid.ts.snap
  tools/hangar/__snapshots__/test_corpus/valid/api.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/capture_containers.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/capture_mutables.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/captures.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/container_types.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/deep_equality.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/issue_2889.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/json.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/mut_container_types.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/resource_captures.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/resource_captures_globals.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/std_containers.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/table.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/website_with_api.test.w_compile_tf-aws.md
Labels: 📐 language-design, 🛠️ compiler

#5059 fix(cli): load test runner for custom platform
  apps/wing/src/commands/test/test.test.ts
  apps/wing/src/commands/test/test.ts
Labels: 👠 platforms, 🐶 dogfood
