Repository winglang/wing, pull requests merged in 2023-12, with the labels that each got.

#4608 feat(cli): add support for `.env` files
  apps/wing/package.json
  apps/wing/src/cli.ts
  apps/wing/src/env.test.ts
  apps/wing/src/env.ts
  docs/docs/06-tools/01-cli.md
  examples/tests/sdk_tests/util/.env
  examples/tests/sdk_tests/util/env.test.w
  libs/wingcompiler/src/compile.ts
  pnpm-lock.yaml
  tools/hangar/__snapshots__/test_corpus/sdk_tests/bucket/signed_url.test.w_test_sim.md
  tools/hangar/src/generated_test_targets.ts
Labels: 🧪 pr/e2e-full

#5160 feat(sdk): more descriptive function names for api gateway handlers in tf-aws
  libs/wingsdk/src/target-tf-aws/api.ts
  libs/wingsdk/test/target-tf-aws/__snapshots__/api.test.ts.snap
  libs/wingsdk/test/target-tf-aws/__snapshots__/tokens.test.ts.snap
  tools/hangar/__snapshots__/test_corpus/sdk_tests/api/404.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/api/aws-api.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/api/cors.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/api/delete.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/api/get.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/api/options.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/api/patch.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/api/path_vars.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/api/post.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/api/put.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/misc/empty-actions.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/website/react-app.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/api.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/api_cors_custom.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/api_cors_default.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/api_valid_path.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/captures.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/inference.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/inherit_stdlib_class.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/issue_2889.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/website_with_api.test.w_compile_tf-aws.md
Labels: 🐶 dogfood

#5247 feat: use typescript with wing cli and worker thread for preflight
  .github/workflows/build.yml
  apps/jsii-docgen/.projen/deps.json
  apps/jsii-docgen/.projen/tasks.json
  apps/jsii-docgen/.projenrc.ts
  apps/jsii-docgen/package.json
  apps/jsii-docgen/test/docgen/view/_npm.test.ts
  apps/vscode-wing/.projen/deps.json
  apps/vscode-wing/.projen/tasks.json
  apps/vscode-wing/.projenrc.ts
  apps/vscode-wing/package.json
  apps/wing-api-checker/.projen/deps.json
  apps/wing-api-checker/.projen/tasks.json
  apps/wing-api-checker/.projenrc.ts
  apps/wing-api-checker/package.json
  examples/ts-fixture/README.md
  examples/ts-fixture/package.json
  examples/ts-fixture/src/main.ts
  examples/ts-fixture/turbo.json
  libs/ts4w/.gitignore
  libs/ts4w/README.md
  libs/ts4w/package.json
  libs/ts4w/src/index.ts
  libs/ts4w/src/internal.ts
  libs/ts4w/test/main.ts
  libs/ts4w/tsconfig.json
  libs/ts4w/tsup.config.ts
  libs/ts4w/turbo.json
  libs/wingcompiler/package.json
  libs/wingcompiler/src/compile.ts
  libs/wingii/src/fixtures/constructs/package.json
  libs/wingsdk/.projen/deps.json
  libs/wingsdk/.projen/tasks.json
  libs/wingsdk/.projenrc.ts
  libs/wingsdk/package.json
  libs/wingsdk/src/core/errors.ts
  libs/wingsdk/src/platform/platform-manager.ts
  libs/wingsdk/src/util/enhanced-error.ts
  pnpm-lock.yaml
  tools/generate-workspace/package.json
  tools/generate-workspace/src/cli.ts
  tools/hangar/__snapshots__/test_corpus/sdk_tests/bucket/signed_url.test.w_test_sim.md
  tools/hangar/package.json
  tools/hangar/src/package.setup.ts
  tools/hangar/src/paths.ts
  tools/hangar/src/typescript/ts4wing.test.ts
  wing.code-workspace
Labels: 🧪 pr/e2e-full

#5296 chore: use `util.waitUntil` in more wing tests
  examples/tests/sdk_tests/bucket/events.test.w
  examples/tests/sdk_tests/function/invoke_async.test.w
  examples/tests/sdk_tests/queue/purge.test.w
  examples/tests/sdk_tests/queue/push.test.w
  examples/tests/sdk_tests/queue/set_consumer.test.w
Labels: 🧪 pr/e2e-full

#5313 chore: hide cloud.api handler functions from wing console ui
  libs/wingsdk/src/target-sim/api.ts
  libs/wingsdk/src/target-tf-aws/api.ts
  libs/wingsdk/test/target-sim/__snapshots__/api.test.ts.snap
Labels: ⚠️ pr/review-mutation

#5167 feat(sdk): add `shell()` and `exec()` to util module
  docs/docs/04-standard-library/util/api-reference.md
  examples/tests/sdk_tests/util/exec.test.w
  examples/tests/sdk_tests/util/shell.test.w
  examples/tests/sdk_tests/util/util.js
  libs/wingc/src/lsp/snapshots/completions/util_static_methods.snap
  libs/wingsdk/src/util/util.ts
  libs/wingsdk/test/core/to-inflight-type.test.ts
  tools/hangar/__snapshots__/test_corpus/sdk_tests/util/exec.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/util/exec.test.w_test_sim.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/util/shell.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/util/shell.test.w_test_sim.md
Labels: 🧪 pr/e2e-full

#5353 chore: ignore bash profile in sdk tests
  examples/tests/sdk_tests/util/exec.test.w
  libs/wingsdk/src/util/util.ts
Labels: 🧪 pr/e2e-full

#5361 feat: emit extern paths as relative
  apps/wing/src/commands/compile.test.ts
  examples/tests/invalid/extern_above.test.w
  libs/wingc/src/jsify.rs
  libs/wingc/src/lib.rs
  libs/wingc/src/lsp/sync.rs
  tools/hangar/__snapshots__/invalid.ts.snap
  tools/hangar/__snapshots__/test_corpus/valid/bring_local.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/bring_wing_library.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/capture_tokens.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/extern_implementation.test.w_compile_tf-aws.md
  tools/hangar/src/generated_test_targets.ts
  tools/hangar/src/utils.ts
Labels: 🧪 pr/e2e-full

#5278 feat: consume wing libraries from javascript/typescript
  apps/wing/src/commands/pack.test.ts
  apps/wing/src/commands/pack.ts
  examples/wing-fixture/index.js
  examples/wing-fixture/package.json
  libs/wingc/src/jsify.rs
  libs/wingii/src/node_resolve.rs
  tools/hangar/__snapshots__/test_corpus/valid/baz.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/bring_local.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/bring_local_dir.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/bring_local_normalization.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/bring_wing_library.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/store.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/valid/struct_from_json.test.w_compile_tf-aws.md
Labels: 🧪 pr/e2e-full
