Repository winglang/wing, pull requests merged in 2024-01, with the labels that each got.

#5434 feat: use a single `.bak` instead of generating `.tmp` directories every time
  apps/wing/src/commands/compile.test.ts
  apps/wing/src/commands/pack.ts
  apps/wing/src/util.ts
  libs/wingcompiler/src/compile.ts
  libs/wingcompiler/src/util.ts
  libs/wingsdk/src/shared/bundling.ts
Labels: 🧪 pr/e2e-full

#4802 fix(sdk): revamp `Bucket.signedUrl()` to handle both GET and PUT actions
  docs/docs/04-standard-library/cloud/bucket.md
  examples/tests/sdk_tests/bucket/signed_url.test.w
  libs/wingc/src/lsp/snapshots/completions/capture_in_test.snap
  libs/wingc/src/lsp/snapshots/completions/incomplete_inflight_namespace.snap
  libs/wingc/src/lsp/snapshots/completions/namespace_middle_dot.snap
  libs/wingc/src/lsp/snapshots/completions/partial_type_reference_annotation.snap
  libs/wingc/src/lsp/snapshots/completions/variable_type_annotation_namespace.snap
  libs/wingsdk/src/cloud/bucket.ts
  libs/wingsdk/src/shared-aws/bucket.inflight.ts
  libs/wingsdk/src/shared-aws/permissions.ts
  tools/hangar/__snapshots__/test_corpus/sdk_tests/bucket/signed_url.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/bucket/signed_url.test.w_test_sim.md
Labels: 🧪 pr/e2e-full

#5439 fix: skip ddb tests on mac/win because no docker support in env
  examples/tests/sdk_tests/dynamodb-table/global-secondary-index.test.w
Labels: 🎨 sdk

#5455 fix(compiler): can't define optional function types
  docs/docs/03-language-reference.md
  examples/tests/invalid/function_type.test.w
  examples/tests/invalid/optionals.test.w
  examples/tests/valid/optionals.test.w
  libs/tree-sitter-wing/grammar.js
  libs/tree-sitter-wing/test/corpus/expressions.txt
  libs/tree-sitter-wing/test/corpus/references.txt
  libs/tree-sitter-wing/test/corpus/statements/statements.txt
  libs/wingc/src/lsp/completions.rs
  libs/wingc/src/parser.rs
  libs/wingc/src/type_check.rs
  tools/hangar/__snapshots__/invalid.ts.snap
  tools/hangar/__snapshots__/test_corpus/valid/optionals.test.w_compile_tf-aws.md
Labels: 🛠️ compiler

#5528 chore: compatibility-spy build fails on PRs from forks
  .github/workflows/build.yml
  libs/compatibility-spy/package.json
  libs/compatibility-spy/src/index.ts
  libs/compatibility-spy/test/spy.test.ts
  libs/compatibility-spy/tsconfig.json
  libs/compatibility-spy/tsup.config.ts
  libs/compatibility-spy/turbo.json
  libs/wingsdk/.projen/tasks.json
  libs/wingsdk/.projenrc.ts
  tools/hangar/__snapshots__/compatibility-spy.ts.snap
  tools/hangar/src/compatibility-spy.test.ts
Labels: 🧪 pr/e2e-full

#5484 fix(compiler): multiline string
  examples/tests/valid/std_string.test.w
  libs/wingc/src/jsify.rs
  tools/bump-pack/src/turbo-diff.ts
  tools/hangar/__snapshots__/test_corpus/valid/std_string.test.w_compile_tf-aws.md
Labels: 🧪 pr/e2e-full

#5541 feat!: native esbuild for bundling
  apps/wing/package.json
  libs/wingc/src/jsify/snapshots/base_class.snap
  libs/wingc/src/jsify/snapshots/chain_functions.snap
  libs/wingc/src/jsify/snapshots/fails_base_class_with_lifted_field_object_unqualified.snap
  libs/wingc/src/jsify/snapshots/fails_lift_collection_of_objects.snap
  libs/wingc/src/jsify/snapshots/fails_lift_with_inflight_arguments.snap
  libs/wingc/src/jsify/snapshots/foo.snap
  libs/wingc/src/jsify/snapshots/identify_field_in_brackets.snap
  libs/wingc/src/jsify/snapshots/identify_field_inside_expression.snap
  libs/wingc/src/jsify/snapshots/inflight_class_extends_inflight_class_inside_inflight_closure.snap
  libs/wingc/src/jsify/snapshots/inflight_inner_class_captures_variable.snap
  libs/wingc/src/jsify/snapshots/some_test.snap
  libs/wingc/src/jsify/snapshots/top_level_inflight_class_extends_inflight_class.snap
  libs/wingc/src/jsify/snapshots/unqualified_lift.snap
  libs/wingsdk/.projen/deps.json
  libs/wingsdk/.projen/tasks.json
  libs/wingsdk/.projenrc.ts
  libs/wingsdk/package.json
  libs/wingsdk/src/core/app.ts
  libs/wingsdk/src/shared/bundling.ts
  libs/wingsdk/test/core/app.test.ts
  package.json
  patches/esbuild-wasm@0.18.20.patch
  pnpm-lock.yaml
  tools/hangar/__snapshots__/plugins.ts.snap
  tools/hangar/__snapshots__/test_corpus/sdk_tests/api/inner_aws_api.test.w_test_sim.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/bucket/aws_bucket.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/bucket/aws_bucket.test.w_test_sim.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/dynamodb-table/aws_dynamodb.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/dynamodb-table/aws_dynamodb.test.w_test_sim.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/dynamodb-table/inner_aws_dynamodb.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/dynamodb-table/inner_aws_dynamodb.test.w_test_sim.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/expect/assert.main.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/expect/assert.main.w_test_sim.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/function/aws_function.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/function/aws_function.test.w_test_sim.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/function/inner_aws_function.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/function/inner_aws_function.test.w_test_sim.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/queue/aws_queue.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/queue/aws_queue.test.w_test_sim.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/queue/inner_aws_queue.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/queue/inner_aws_queue.test.w_test_sim.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/table/aws_table.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/table/aws_table.test.w_test_sim.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/table/inner_aws_table.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/table/inner_aws_table.test.w_test_sim.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/testing/assert-equal-string.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/testing/assert-equal-string.w_test_sim.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/testing/assert.main.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/testing/assert.main.w_test_sim.md
  tools/hangar/__snapshots__/test_corpus/valid/assertions.w_compile_tf-aws.md
  tools/hangar/src/package.setup.ts
Labels: 🧪 pr/e2e-full

#5550 feat: improved sourcemaps with relative paths and better relative handling for extern
  examples/tests/error/inflight_stacktraces.test.w
  examples/tests/invalid/extern_above.test.w
  examples/tests/invalid/lib/extern_above.w
  examples/wing-fixture/subdir/util.w
  libs/wingc/src/jsify.rs
  libs/wingsdk/src/shared/bundling.ts
  libs/wingsdk/src/simulator/client.ts
  libs/wingsdk/src/util/enhanced-error.ts
  libs/wingsdk/test/target-sim/__snapshots__/topic.test.ts.snap
  libs/wingsdk/test/target-sim/topic.test.ts
  tools/hangar/__snapshots__/error.ts.snap
  tools/hangar/__snapshots__/invalid.ts.snap
  tools/hangar/__snapshots__/test_corpus/sdk_tests/bucket/signed_url.test.w_test_sim.md
  tools/hangar/__snapshots__/test_corpus/valid/bring_wing_library.test.w_compile_tf-aws.md
  tools/hangar/src/invalid.test.ts
  tools/hangar/src/utils.ts
Labels: 🧪 pr/e2e-full

#5586 feat: `wing test` recursively finds entrypoints by default, and simpler filename filtering
  apps/wing/src/commands/compile.ts
  apps/wing/src/commands/run.ts
  apps/wing/src/commands/test/test.test.ts
  apps/wing/src/commands/test/test.ts
  docs/docs/06-tools/01-cli.md
  libs/wingcompiler/package.json
Labels: 🧪 pr/e2e-full

#5580 chore: switch to Node LTS (v20) for internal dev and recommend it for users
  .devcontainer/devcontainer.json
  .github/workflows/build.yml
  .github/workflows/tf-aws-test.yml
  .node-version
  apps/jsii-docgen/.projen/deps.json
  apps/jsii-docgen/.projenrc.ts
  apps/jsii-docgen/package.json
  apps/jsii-docgen/test/__fixtures__/libraries/construct-library/package.json
  apps/vscode-wing/.projen/deps.json
  apps/vscode-wing/.projenrc.ts
  apps/vscode-wing/package.json
  apps/wing-api-checker/.projen/deps.json
  apps/wing-api-checker/.projenrc.ts
  apps/wing-api-checker/package.json
  apps/wing-console/console/app/package.json
  apps/wing-console/console/app/preview/Dockerfile
  apps/wing/package.json
  docs/contributing/01-start-here/05-development.md
  docs/docs/01-start-here/02-installation.md
  docs/docs/08-guides/02-ci-cd.md
  examples/ts-fixture/package.json
  examples/wing-fixture/package.json
  libs/@wingcloud/framework/package.json
  libs/wingcompiler/package.json
  libs/wingii/src/fixtures/constructs/package.json
  libs/wingsdk/.projen/deps.json
  libs/wingsdk/.projenrc.ts
  libs/wingsdk/package.json
  libs/wingsdk/src/target-tf-azure/function.ts
  libs/wingsdk/test/target-sim/__snapshots__/api.test.ts.snap
  libs/wingsdk/test/target-tf-azure/__snapshots__/function.test.ts.snap
  package.json
  pnpm-lock.yaml
  tools/bump-pack/package.json
  tools/compatibility-matrix-automation/package.json
  tools/generate-workspace/package.json
  tools/hangar/package.json
Labels: 🧪 pr/e2e-full
