Repository winglang/wing, pull requests merged in 2024-04, with the labels that each got.

#6152 fix: missing uncaught inflight exceptions when debugging
  docs/docs/06-tools/03-debugging.md
  libs/wingsdk/src/shared/sandbox.ts
Labels: 🧪 pr/e2e-full

#6222 chore: update rust and wasi toolchain
  .cargo/config.toml
  libs/wingc/package.json
  libs/wingc/src/type_check/lifts.rs
  rust-toolchain.toml
  scripts/setup_wasi.sh
Labels: 🧪 pr/e2e-full

#6217 fix: unable to hit most inflight breakpoints while debugging
  apps/vscode-wing/.projenrc.ts
  apps/vscode-wing/package.json
  apps/vscode-wing/src/extension.ts
  apps/vscode-wing/src/project/vscode_types.ts
  docs/docs/06-tools/03-debugging.md
  libs/wingsdk/.projen/deps.json
  libs/wingsdk/.projenrc.ts
  libs/wingsdk/package.json
  libs/wingsdk/src/shared/bundling.ts
  libs/wingsdk/src/shared/sandbox.ts
  libs/wingsdk/test/shared/bundling.test.ts
  pnpm-lock.yaml
Labels: 🧪 pr/e2e-full

#6247 feat: support file browser in bring ui
  apps/wing-console/console/app/demo/main.w
  apps/wing-console/console/server/src/router/app.ts
  apps/wing-console/console/server/src/router/bucket.ts
  apps/wing-console/console/server/src/router/file-browser.ts
  apps/wing-console/console/server/src/router/http-client.ts
  apps/wing-console/console/server/src/router/index.ts
  apps/wing-console/console/server/src/router/ui-button.ts
  apps/wing-console/console/server/src/router/ui-field.ts
  apps/wing-console/console/ui/src/features/bucket-interaction-view.tsx
  apps/wing-console/console/ui/src/features/file-browser-view.tsx
  apps/wing-console/console/ui/src/services/use-bucket.ts
  apps/wing-console/console/ui/src/ui/custom-resource-file-browser.tsx
  apps/wing-console/console/ui/src/ui/custom-resource-http-client.tsx
  apps/wing-console/console/ui/src/ui/custom-resource-item.tsx
  apps/wing-console/console/ui/src/ui/custom-resource-ui-button.tsx
  apps/wing-console/console/ui/src/ui/custom-resource-ui-field.tsx
  apps/wing-console/console/ui/src/ui/file-browser.tsx
  apps/wing-console/console/ui/src/ui/resource-metadata.tsx
  docs/docs/04-standard-library/ui/api-reference.md
  libs/wingsdk/src/core/tree.ts
  libs/wingsdk/src/ui/file-browser.delete.inflight.ts
  libs/wingsdk/src/ui/file-browser.get.inflight.ts
  libs/wingsdk/src/ui/file-browser.list.inflight.ts
  libs/wingsdk/src/ui/file-browser.put.inflight.ts
  libs/wingsdk/src/ui/file-browser.ts
  libs/wingsdk/src/ui/index.ts
Labels: ⚠️ pr/review-mutation

#5951 rfc: explicit lift qualification
  docs/contributing/999-rfcs/2024-03-14-explicit-lift-qualification.md
Labels: Stale

#6331 chore: fix test failure in CI
  examples/tests/sdk_tests/container/mount.test.w
Labels: 🧪 pr/e2e-full

#6336 feat(sdk): reuse volumes for sim.Container
  examples/tests/sdk_tests/container/mount.test.w
  libs/wingsdk/src/target-sim/container.inflight.ts
  libs/wingsdk/src/target-sim/container.md
  libs/wingsdk/test/target-sim/container.test.ts
  libs/wingsdk/test/target-sim/my-docker-image.mounted-volume/index.js
  tools/hangar/__snapshots__/test_corpus/sdk_tests/container/mount.test.w_test_sim.md
Labels: 🧪 pr/e2e-full

#6348 fix(cli)!: .env file not loaded when compiling outside sourceDir
  apps/wing/src/cli.ts
  apps/wing/src/commands/compile.ts
  apps/wing/src/commands/pack.ts
  apps/wing/src/commands/run.ts
  apps/wing/src/env.ts
  libs/wingsdk/src/target-sim/secret.inflight.ts
Labels: 🧪 pr/e2e-full

#5342 feat(sdk): add `util.spawn()`
  docs/docs/04-standard-library/util/api-reference.md
  examples/tests/sdk_tests/util/spawn.test.w
  libs/wingc/src/lsp/snapshots/completions/util_static_methods.snap
  libs/wingsdk/src/util/child-process.ts
  libs/wingsdk/src/util/index.ts
  libs/wingsdk/src/util/util.ts
  tools/hangar/__snapshots__/test_corpus/sdk_tests/util/spawn.test.w_compile_tf-aws.md
  tools/hangar/__snapshots__/test_corpus/sdk_tests/util/spawn.test.w_test_sim.md
Labels: 🧪 pr/e2e-full
